site_name: My Tasks

theme:
  name: material
  language: pt-BR
  favicon: assets/tasks.png
  logo: assets/tasks.png

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - tables
  - codehilite
  - admonition
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css